import { v4 as uuidv4 } from 'uuid';
import { EvidenceItem, Interaction, PreparationBrief, PostInteractionAnalysis, PlanVsActual, RoleplayConfig } from './types';
import { semantic, strings, confidence } from './semantic-client';
import { scenarioContext } from './product-spec';
import { evaluateEvidence } from './assessment-service';

export async function analyzeSemantically(transcript:string, interaction:Interaction, brief:PreparationBrief, sourceId=uuidv4()):Promise<PostInteractionAnalysis> {
 const lines=transcript.split(/\r?\n/); const context=scenarioContext(interaction);
 const extracted=await semantic('TRANSCRIPT_FACT_EXTRACTION','Extract only factual events from the transcript. Return {"facts":[{"line":1,"speaker":"exact label before colon","sourceText":"exact quote","eventType":"OBJECTION|QUESTION|CLARIFICATION|VALUE_STATEMENT|CONCESSION|COMMITMENT|NEXT_STEP|COMPETITOR_REFERENCE|BUSINESS_PAIN|DECISION_CRITERIA|RISK|ESCALATION|OTHER","confidence":0.8}]}. No inference or coaching.',{lines:lines.map((text,i)=>({line:i+1,text}))});
 if(!Array.isArray(extracted.facts))throw new Error('Invalid transcript fact output');
 const seen=new Set<string>();
 const facts=extracted.facts.flatMap((f:any,index:number)=>{
   const line=Number(f.line),text=lines[line-1];const quote=typeof f.sourceText==='string'?f.sourceText.trim():'';
   if(!Number.isInteger(line)||!text||quote.length<3||!text.includes(quote)||!text.includes(':'))return [];
   const speaker=text.slice(0,text.indexOf(':')).trim(); if(typeof f.speaker!=='string'||f.speaker.trim().toLowerCase()!==speaker.toLowerCase())return [];
   const key=`${line}:${quote}`;if(seen.has(key))return [];seen.add(key);
   const employee=speaker.toLowerCase()===(interaction.employeeSpeaker||'You').toLowerCase()||/^(you|employee|seller|salesperson|rep|account executive)$/i.test(speaker);
   return [{id:`${sourceId}:fact-${index+1}`,line,speaker,sourceText:quote,eventType:['OBJECTION','QUESTION','CLARIFICATION','VALUE_STATEMENT','CONCESSION','COMMITMENT','NEXT_STEP','COMPETITOR_REFERENCE','BUSINESS_PAIN','DECISION_CRITERIA','RISK','ESCALATION','OTHER'].includes(f.eventType)?f.eventType:'OTHER',confidence:confidence(f.confidence),speakerType:employee?'EMPLOYEE':'STAKEHOLDER'}];
 });
 const behavior=await semantic('BEHAVIOR_EXTRACTION','Translate facts into observable employee behaviors. Return {"behaviors":[{"description":"","evidenceIds":[],"classification":"OBSERVED|INFERRED"}]}. Each behavior must cite supplied facts. Missing behavior can only be diagnosed when the transcript contains an opportunity. Do not score stakeholder statements.',{facts,context});
 if(!Array.isArray(behavior.behaviors))throw new Error('Invalid behavior extraction');
 const employeeFacts=new Map(facts.filter((f:any)=>f.speakerType==='EMPLOYEE').map((f:any)=>[f.id,f]));
 const evidence:EvidenceItem[]=behavior.behaviors.flatMap((b:any)=>strings(b.evidenceIds).filter(id=>employeeFacts.has(id)).map(id=>{
   const f=employeeFacts.get(id) as any;return {evidenceId:id,interactionId:interaction.id,sessionId:sourceId,sourceId,sourceType:'TRANSCRIPT' as const,speaker:f.speaker,sourceText:f.sourceText,behaviorObserved:String(b.description||''),statement:String(b.description||''),source:'transcript' as const,classification:b.classification==='OBSERVED'?'OBSERVED' as const:'INFERRED' as const,confidence:f.confidence,capability:context.targetCapability,timestamp:new Date().toISOString(),lineReference:`Line ${f.line}`};
 })).filter((e:EvidenceItem,index:number,all:EvidenceItem[])=>all.findIndex(x=>x.evidenceId===e.evidenceId)===index);
 const intended=brief.intendedBehaviors?.length?brief.intendedBehaviors:[{id:`${brief.id}-legacy`,behavior:brief.personalCoachingFocus,priority:'high',successCriterion:brief.practiceRecommendation}];
 const comparison=await semantic('PLAN_VS_ACTUAL','Compare each supplied intended behavior with transcript facts. Return {"rows":[{"behaviorId":"supplied id","actual":"","evidenceIds":[],"impact":"Low|Medium|High","confidence":0,"whyItMatters":"","execution":"SUCCESSFUL|MISSED|NOT_OBSERVABLE"}]}. Actual must cite facts. MISSED requires an observed opportunity; silence alone is NOT_OBSERVABLE. Do not introduce a new intended behavior.',{intendedBehaviors:intended,facts,behaviors:behavior.behaviors});
 if(!Array.isArray(comparison.rows))throw new Error('Invalid Plan vs Actual output');
 const rows:PlanVsActual[]=intended.map(b=>{
   const r=comparison.rows.find((row:any)=>row.behaviorId===b.id); const cited=strings(r?.evidenceIds).filter(id=>facts.some((f:any)=>f.id===id));
   const observable=cited.some(id=>employeeFacts.has(id));
   return {intended:b.behavior,intendedSource:`${brief.id}:${b.id}`,actual:observable?String(r.actual||'NOT OBSERVED'):'NOT OBSERVED',actualSource:observable?cited.join(', '):sourceId,evidenceIds:observable?cited:[],sourceText:observable?facts.filter((f:any)=>cited.includes(f.id)).map((f:any)=>`Line ${f.line}: ${f.sourceText}`).join(' · '):undefined,impact:['Low','Medium','High'].includes(r?.impact)?r.impact:'Low',confidence:observable?confidence(r.confidence):0,whyItMatters:observable?String(r.whyItMatters||''):'No supported execution claim is available.',explanation:observable?String(r.whyItMatters||''):'Not observable in this transcript',observation:observable?'OBSERVED':'NOT_OBSERVED',execution:observable&&['SUCCESSFUL','MISSED'].includes(r.execution)?r.execution:'NOT_OBSERVABLE'};
 });
 const config:RoleplayConfig={stakeholderRole:interaction.stakeholderRole||'Stakeholder',objectives:[interaction.objective],likelyObjections:brief.likelyObjections,personality:'',pressureLevel:context.complexityProfile.pressure as 'low'|'medium'|'high',commercialConstraints:'Only supplied policy',hiddenPriorities:[],desiredOutcome:interaction.objective,interactionId:interaction.id,targetCapability:context.targetCapability,complexityProfile:context.complexityProfile,intendedBehaviors:brief.intendedBehaviors};
 const score=await evaluateEvidence(evidence,config,{facts,rows,intended});
 const groundedRows=rows.map((r,index):PlanVsActual=>r.observation==='OBSERVED'&&!score.approvedRows?.includes(index)?{...r,actual:'NOT OBSERVED',evidenceIds:[],sourceText:undefined,observation:'NOT_OBSERVED',execution:'NOT_OBSERVABLE',confidence:0,whyItMatters:'The comparison could not be grounded in the supplied evidence.',explanation:'Insufficient evidence'}:r);
 const coaching=await semantic('INTERVENTION_GENERATION','Generate ONE primary intervention from the supported diagnosis. If no score/evidence exists, recommend obtaining a fuller transcript; do not invent a weakness. Return {"title":"","targetBehavior":"","whyItMatters":"","exercise":"","difficulty":"low|medium|high","successCriterion":"","evidenceIds":[]}. Use the current context and prior learning to adapt the exercise rather than repeat the same scenario.',{diagnosis:score,context,priorLearning:brief.priorLearning,intendedBehaviors:intended});
 for(const key of ['title','targetBehavior','whyItMatters','exercise','successCriterion'])if(typeof coaching[key]!=='string'||!coaching[key].trim())throw new Error('Incomplete coaching output');
 const intervention={id:uuidv4(),interactionId:interaction.id,title:score.score?coaching.title:'Collect fuller evidence',description:score.score?coaching.whyItMatters:'An employee assessment requires observable source evidence.',targetCapability:context.targetCapability,targetBehavior:score.score?coaching.targetBehavior:'Supply attributable employee turns',behaviour:score.score?coaching.targetBehavior:'Supply attributable employee turns',whyItMatters:score.score?coaching.whyItMatters:'The available transcript does not support an employee assessment.',exercise:score.score?coaching.exercise:'Add a fuller speaker-labelled transcript',difficulty:(['low','medium','high'].includes(coaching.difficulty)?coaching.difficulty:'medium') as 'low'|'medium'|'high',successCriterion:score.score?coaching.successCriterion:'Transcript includes relevant employee turns and context',recommendedAction:score.score?coaching.exercise:'Add a fuller speaker-labelled transcript',estimatedDuration:'5 minutes',priority:'medium' as const,evidenceIds:strings(coaching.evidenceIds).filter(id=>score.evidence.some(e=>e.evidenceId===id))};
 if(score.score&&!intervention.evidenceIds.length)throw new Error('Coaching did not cite the supported diagnosis. Please retry.');
 score.recommendedIntervention=intervention.recommendedAction;
 return {id:uuidv4(),interactionId:interaction.id,transcriptId:sourceId,planVsActual:groundedRows,capabilityDiagnosis:[score],strengths:score.strength?[score.strength]:[],missedOpportunities:score.weakness?[score.weakness]:[],repeatedPatterns:[],likelyImpact:score.score?`Primary development focus: ${score.weakness||context.targetCapability}. Confidence: ${score.confidence>=0.75?'High':score.confidence>=0.5?'Medium':'Low'}.`:'Insufficient observed employee evidence for a capability diagnosis.',nextIntervention:intervention,generatedAt:new Date().toISOString()};
}
