import { test, expect } from '@playwright/test';
import { gateway, login, create, plan, saved } from './consolidated-fixture';
test.use({launchOptions:process.env.PLAYWRIGHT_CHROME_PATH?{executablePath:process.env.PLAYWRIGHT_CHROME_PATH}:{},video:'off'});

test('complete live-contract journey adapts the next plan and preserves artifact identities',async({page})=>{
 const calls=await gateway(page),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await login(page);await plan(page);
 await expect(page.getByRole('heading',{name:'Your Strategy'})).toBeVisible();
 let s=await saved(page);expect(s.interactions[0].status).toBe('PREPARED');expect(s.briefs[0].items[0].classification).toBe('INFERRED');expect(s.briefs[0].commercialGuidance.discountLimits).toBe('Not provided');
 await page.getByRole('button',{name:'Practice this moment',exact:true}).first().click();
 await expect(page.getByText('I am concerned about the delivery timeline.',{exact:true})).toBeVisible();
 await page.getByPlaceholder('Respond naturally as yourself...').fill('What is driving the delivery concern?');await page.getByPlaceholder('Respond naturally as yourself...').press('Enter');
 await expect(page.getByText('The delivery timeline is my concern. What is the next step?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'End & evaluate'}).click();
 await expect(page.getByRole('heading',{name:'Practice Results',exact:true})).toBeVisible();s=await saved(page);
 expect(s.interactions[0].status).toBe('READY');expect(s.practiceSessions[0].completionReason).toBe('USER_END');expect(s.capabilityHistory[0].patterns).toEqual([]);expect(s.practiceEvaluations[0].capabilityScores[0].dimensions.Advancement).toBeNull();
 await page.getByRole('button',{name:"I've done the real meeting"}).first().click();await page.getByPlaceholder(/Paste the meeting transcript here/).fill('Customer: Delivery worries me.\nYou: What is the largest delivery risk?\nCustomer: The handover.');await page.getByRole('button',{name:'Analyze Interaction'}).click();
 await expect(page.getByText("You prepared for this. Here's what actually happened.")).toBeVisible();s=await saved(page);
 expect(s.interactions[0].status).toBe('ANALYZED');expect(s.interactions[0].analysisId).toBe(s.analyses[0].id);expect(s.analyses[0].transcriptId).toBe(s.transcripts[0].id);expect(s.analyses[0].planVsActual[0].intendedSource).toContain(s.briefs[0].intendedBehaviors[0].id);expect(s.analyses[0].planVsActual[0].sourceText).toContain('What is the largest delivery risk?');
 await page.getByRole('button',{name:/Prepare the next performance moment/}).click();await page.getByPlaceholder('e.g., Renewal Meeting').fill('Next review');await page.getByPlaceholder('e.g., Acme Corporation').fill('Acme');await page.getByRole('button',{name:'Generate Preparation Brief'}).click();await expect(page.getByRole('heading',{name:'What we learned last time'})).toBeVisible();
 s=await saved(page);expect(s.interactions[1].previousInteractionId).toBe(s.interactions[0].id);expect(s.briefs[1].priorLearning).toContain('Practice the final commitment');
 const ops=calls.map(c=>c.options?.operation).filter(Boolean);expect(ops.indexOf('PRACTICE_EVIDENCE_EXTRACTION')).toBeLessThan(ops.indexOf('CAPABILITY_EVALUATION'));expect(errors).toEqual([]);
});
test('intake requires explicit replacement and taxonomy changes real prompt context',async({page})=>{
 const calls=await gateway(page);await login(page);await create(page);
 await page.getByLabel('What are you preparing for?',{exact:true}).fill('Renewal with Acme CFO');await page.getByRole('button',{name:'Suggest interaction details'}).click();await expect(page.getByText('Review suggested details')).toBeVisible();expect(await page.getByPlaceholder('e.g., Acme Corporation').inputValue()).toBe('Acme');
 await page.getByLabel('Suggested customer').fill('Reviewed Acme');await page.locator('label').filter({has:page.getByLabel('Suggested customer')}).getByRole('checkbox').check();await page.getByRole('button',{name:'Apply selected suggestions'}).click();expect(await page.getByPlaceholder('e.g., Acme Corporation').inputValue()).toBe('Reviewed Acme');
 expect(await page.getByLabel('Performance moment',{exact:true}).locator('option').count()).toBe(28);await page.getByLabel('Performance moment',{exact:true}).selectOption('technical-discovery');await page.getByLabel('Experience / complexity',{exact:true}).selectOption('Executive');await page.getByLabel('Stakeholder seniority',{exact:true}).selectOption('Director');await page.getByRole('button',{name:'Generate Preparation Brief'}).click();await expect(page.getByRole('heading',{name:'Performance Plan',exact:true})).toBeVisible();
 const p=JSON.parse(calls.find(c=>c.options?.operation==='PERFORMANCE_PLAN_GENERATION').messages[1].content);expect(p.context.performanceMoment.id).toBe('technical-discovery');expect(p.context.experienceLevel).toBe('Executive');expect(p.context.stakeholderSeniority).toBe('Director');expect(p.context.targetCapability).toBe('Discovery');
});
test('demo runs the full loop without backend calls and never changes live memory',async({page})=>{
 await gateway(page);await login(page);const live=await saved(page);let semanticCalls=0;page.on('request',r=>{if(r.url().includes('/api/ai/'))semanticCalls++;});
 await page.getByLabel('Application mode').selectOption('DEMO');await page.getByPlaceholder('Your name').fill('Demo Employee');await page.getByPlaceholder('your.email@company.com').fill('demo@example.com');await page.getByRole('button',{name:'Sign In',exact:true}).click();
 await page.getByRole('button',{name:'Prepare me',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Performance Plan',exact:true})).toBeVisible();expect((await saved(page,'DEMO')).interactions).toHaveLength(1);
 await page.getByRole('button',{name:'Practice this moment',exact:true}).first().click();for(const text of ['What is the concern?','What would reduce the risk?','Let us set an owner and date.']){await expect(page.getByPlaceholder('Respond naturally as yourself...')).toBeEnabled();await page.getByPlaceholder('Respond naturally as yourself...').fill(text);await page.getByPlaceholder('Respond naturally as yourself...').press('Enter');}
 await expect(page.getByRole('heading',{name:'Practice Results',exact:true})).toBeVisible();await page.getByRole('button',{name:"I've done the real meeting"}).first().click();await page.getByRole('button',{name:'Load Demo Transcript'}).click();await page.getByRole('button',{name:'Analyze Interaction'}).click();await expect(page.getByText("You prepared for this. Here's what actually happened.")).toBeVisible();expect(semanticCalls).toBe(0);
 await page.getByLabel('Application mode').selectOption('LIVE');await expect(page.getByRole('heading',{name:'AI Performance Coach',exact:true})).toBeVisible();expect((await saved(page)).interactions).toEqual(live.interactions);expect((await saved(page)).capabilityHistory).toEqual(live.capabilityHistory);
});
for(const failure of ['CONTEXT_RISK_INTERPRETATION','ROLEPLAY','CAPABILITY_EVALUATION'])test('provider failure at '+failure+' creates no assessment or fallback',async({page})=>{
 await gateway(page,{fail:failure});await login(page);await create(page);await page.getByRole('button',{name:'Generate Preparation Brief'}).click();
 if(failure==='CONTEXT_RISK_INTERPRETATION')await expect(page.getByRole('heading',{name:'Performance plan unavailable'})).toBeVisible();
 else{await expect(page.getByRole('heading',{name:'Performance Plan',exact:true})).toBeVisible();await page.getByRole('button',{name:'Practice this moment',exact:true}).first().click();if(failure==='ROLEPLAY')await expect(page.getByText('Practice could not be completed. No performance assessment was generated.',{exact:true})).toBeVisible();else{await expect(page.getByPlaceholder('Respond naturally as yourself...')).toBeEnabled();await page.getByPlaceholder('Respond naturally as yourself...').fill('What concerns you?');await page.getByPlaceholder('Respond naturally as yourself...').press('Enter');await expect(page.getByText('The delivery timeline is my concern. What is the next step?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'End & evaluate'}).click();await expect(page.getByRole('heading',{name:'Practice Could Not Be Completed'})).toBeVisible();}}
 const s=await saved(page);expect(s.practiceEvaluations).toEqual([]);expect(s.capabilityHistory).toEqual([]);expect(s.mode).toBe('LIVE');expect(s.interactions[0].status).toBe(failure==='CONTEXT_RISK_INTERPRETATION'?'PREPARATION_FAILED':'PRACTICE_FAILED');
});
test('outage blocks gate one and leaves dependent gates not run',async({page})=>{await gateway(page,{fail:'all'});await login(page);await page.getByRole('button',{name:'MVP Validation',exact:true}).click();await page.getByRole('button',{name:'Run Validation Suite'}).click();await expect(page.getByText('BLOCKED',{exact:true})).toBeVisible();await expect(page.getByText('NOT RUN',{exact:true})).toHaveCount(4);});
test('malformed semantic output fails preparation cleanly',async({page})=>{await gateway(page,{malformed:'PERFORMANCE_PLAN_GENERATION'});await login(page);await create(page);await page.getByRole('button',{name:'Generate Preparation Brief'}).click();await expect(page.getByRole('heading',{name:'Performance plan unavailable'})).toBeVisible();expect((await saved(page)).briefs).toEqual([]);});
