import { PreparationBrief } from '../types';
export default function PlanContent({brief:b}:{brief:PreparationBrief}){
 const risk=b.personalPerformanceRisk;
 return <div className="space-y-4">
 <p className="text-sm font-semibold text-primary-700">{b.sourceMode==='COMPANY_COACH'?'Company Coach · Supplied company context':'General Coach · Company information not connected'}</p>
 {b.priorLearning&&<section className="p-4 bg-violet-50 border rounded-xl"><h2 className="font-semibold">What we learned last time</h2><p>{b.priorLearning}</p></section>}
 <section className="p-6 bg-primary-700 text-white rounded-2xl"><h2 className="text-sm font-semibold">Meeting Objective</h2><p className="text-xl mt-2">{b.objective}</p></section>
 <section className="p-5 border bg-white rounded-xl"><h2 className="font-bold text-lg">Your Performance Risk</h2><p className="mt-2">{risk?.behavior||b.personalCoachingFocus}</p><p className="text-sm text-surface-600 mt-2">{risk?.meetingImplication}</p><p className="mt-2"><strong>Success behavior:</strong> {risk?.successBehavior||b.practiceRecommendation}</p><details className="text-sm mt-4"><summary className="font-semibold">Why your coach is focusing here</summary><p className="mt-2">{b.personalization?.evidenceCount||0} relevant prior observations · {b.personalization?.pattern||'No recurring pattern established'}</p><p>{b.personalization?.context}</p><p>Confidence: {(b.personalization?.confidence||0)>=.75?'High':(b.personalization?.confidence||0)>=.5?'Medium':'Low'} · {b.whyPersonalized}</p></details></section>
 <section className="p-5 border bg-white rounded-xl"><h2 className="font-bold text-lg">Your Strategy</h2><ol className="list-decimal pl-5 mt-2 space-y-3">{(b.intendedBehaviors||[]).map(i=><li key={i.id}><strong>{i.behavior}</strong><p className="text-sm text-surface-600">Success: {i.successCriterion}</p></li>)}</ol></section>
 <section className="p-5 border bg-white rounded-xl"><h2 className="font-bold text-lg">Questions Worth Asking</h2><ol className="list-decimal pl-5 mt-2 space-y-2">{b.recommendedQuestions.slice(0,3).map(q=><li key={q}>{q}</li>)}</ol>{b.recommendedQuestions.length>3&&<details className="mt-3 text-sm"><summary>More questions</summary>{b.recommendedQuestions.slice(3).map(q=><p key={q} className="mt-2">{q}</p>)}</details>}</section>
 <section className="p-5 border bg-amber-50 rounded-xl"><h2 className="font-bold text-lg">Watch Out For</h2>{(b.watchOuts||[]).slice(0,3).map(w=><div key={w.behavior} className="mt-3"><strong>{w.behavior}</strong><p className="text-sm">{w.whyItMatters}</p><p className="text-sm">Instead: {w.preferredAlternative}</p></div>)}</section>
 <section className="p-5 border bg-white rounded-xl"><h2 className="font-bold text-lg">Practice This Moment</h2><p className="mt-2">{b.practiceRecommendation}</p></section>
 <details className="p-5 border bg-white rounded-xl"><summary className="font-semibold">Context, provenance and commercial guidance</summary><div className="mt-4 space-y-3">{(b.items||[]).map((i,n)=><div key={n}><span className="text-xs font-bold text-primary-700">{i.classification}</span><p>{i.text}</p><p className="text-xs text-surface-500">Source: {i.source}</p></div>)}<h3 className="font-semibold">Stakeholder priorities · hypotheses unless cited above</h3>{b.stakeholderPriorities.map(p=><p key={p}>{p}</p>)}<h3 className="font-semibold">What we don’t know</h3>{b.unknowns?.map(p=><p key={p}>{p}</p>)}<h3 className="font-semibold">Positioning · recommendation</h3>{b.recommendedPositioning.map(p=><p key={p}>{p}</p>)}<h3 className="font-semibold">Commercial Guidance</h3><p>Discount authority: {b.commercialGuidance.discountLimits}</p><p>Relevant package: {b.commercialGuidance.relevantPackage}</p><p>Escalation path: {b.commercialGuidance.escalationItems.join('; ')}</p></div></details>
 </div>;
}
