import { taxonomy, profiles, rubricLibrary } from '../product-spec';
import { useState, useRef, useEffect } from 'react';
import { extractInteractionCandidates } from '../performance-intelligence';
export function SmartIntake({current,apply}:{current:Record<string,string>;apply:(values:Record<string,string>)=>void}){
 const [text,setText]=useState(''),[candidates,setCandidates]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const active=useRef(true);useEffect(()=>()=>{active.current=false;},[]);
 async function extract(){setBusy(true);setError('');try{const values=await extractInteractionCandidates(text);if(active.current){setCandidates(values);setSelected([]);}}catch{if(active.current)setError('The coach could not extract suggestions. Retry or fill in the form below.');}finally{if(active.current)setBusy(false);}}
 return <section className="mb-6 p-4 bg-slate-50 rounded-xl border"><label className="block font-semibold">What are you preparing for?<textarea aria-label="What are you preparing for?" value={text} onChange={e=>setText(e.target.value)} placeholder="Renewal with Acme CFO tomorrow. They are concerned about price and implementation delays…" className="block w-full mt-2 p-3 border rounded-lg"/></label><button disabled={busy||!text.trim()} onClick={extract} className="mt-3 px-4 py-2 bg-primary-600 text-white rounded-lg disabled:opacity-50">{busy?'Extracting suggestions…':'Suggest interaction details'}</button>{error&&<p role="alert" className="mt-2 text-red-700">{error}</p>}{Object.keys(candidates).length>0&&<div className="mt-4"><h3 className="font-semibold">Review suggested details</h3><p className="text-sm">Select values to apply. Existing values are shown before you replace them.</p>{Object.entries(candidates).map(([key,value])=><label key={key} className="block mt-3 text-sm"><input type="checkbox" checked={selected.includes(key)} onChange={e=>setSelected(s=>e.target.checked?[...s,key]:s.filter(k=>k!==key))}/> {key}{current[key]&&<span className="block text-amber-800">Current: {current[key]}</span>}<input aria-label={`Suggested ${key}`} value={value} onChange={e=>setCandidates(c=>({...c,[key]:e.target.value}))} className="block border p-2 rounded w-full"/></label>)}<button disabled={!selected.length} onClick={()=>{const values=Object.fromEntries(selected.map(k=>[k,candidates[k]]));if(values.interactionType&&!taxonomy.some(m=>m.id===values.interactionType)||values.experienceLevel&&!(values.experienceLevel in profiles)||values.focusCapability&&!(values.focusCapability in rubricLibrary)){setError('Choose a valid performance moment, experience level and capability from the form below.');return;}apply(values);setCandidates({});}} className="mt-3 border px-4 py-2 rounded-lg">Apply selected suggestions</button></div>}</section>;
}
